//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_MailerMainDBEntities : DbContext
    {
        public E_MailerMainDBEntities()
            : base("name=E_MailerMainDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_email_attachment> tbl_email_attachment { get; set; }
        public virtual DbSet<tbl_email_awaiting> tbl_email_awaiting { get; set; }
        public virtual DbSet<tbl_email_awaiting_details> tbl_email_awaiting_details { get; set; }
        public virtual DbSet<tbl_email_to_address> tbl_email_to_address { get; set; }
        public virtual DbSet<tbl_setting> tbl_setting { get; set; }
    }
}
