//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_email_sent_adress
    {
        public string guid { get; set; }
        public string str_email_address { get; set; }
        public string str_email_name { get; set; }
        public Nullable<int> int_type { get; set; }
        public string email_guid { get; set; }
    
        public virtual tbl_email_sent tbl_email_sent { get; set; }
    }
}
