//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_email_attachment
    {
        public string guid { get; set; }
        public string str_file_path { get; set; }
        public Nullable<bool> bit_attached { get; set; }
        public string str_error { get; set; }
        public string email_detail_guid { get; set; }
    
        public virtual tbl_email_awaiting_details tbl_email_awaiting_details { get; set; }
    }
}
