//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_email_sent
    {
        public tbl_email_sent()
        {
            this.tbl_email_sent_adress = new HashSet<tbl_email_sent_adress>();
        }

        public string guid { get; set; }
        public Nullable<int> int_status { get; set; }
        public string str_error { get; set; }
        public Nullable<System.DateTime> dt_due_date { get; set; }
        public Nullable<System.DateTime> dt_inserted_date { get; set; }
        public Nullable<System.DateTime> dt_send_date { get; set; }
        public Nullable<System.DateTime> dt_expire_date { get; set; }
        public Nullable<int> int_failed_count { get; set; }
        public string email_detail_guid { get; set; }
    
        public virtual tbl_email_awaiting_details tbl_email_awaiting_details { get; set; }
        public virtual ICollection<tbl_email_sent_adress> tbl_email_sent_adress { get; set; }
    }
}
